apiVersion: v1
kind: Service
metadata:
  name: whoami-service
  labels:
    app: whoami
{{- $service := .Values.service | default dict }}
spec:
  type: {{ $service.type | default "ClusterIP" }}
  selector:
    app: whoami
  ports:
    - name: http
      port: {{ $service.port | default 80 }}
      targetPort: 80
      protocol: TCP