apiVersion: v1
kind: Service
metadata:
  name: whoami-service
  labels:
    app: whoami
spec:
  type: {{ .Values.service.type }}
  selector:
    app: whoami
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP