apiVersion: v1
kind: Service
metadata:
  name: whoami-service
  labels:
    app: whoami
resources:
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
