apiVersion: v1
kind: Service
metadata:
  name: technitium-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    app: technitium
  ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: technitium-lb
  namespace: {{ .Release.Namespace }}
  annotations:
    metallb.universe.tf/loadBalancerIPs: {{ .Values.service.loadBalancerIP }}
spec:
  type: LoadBalancer
  selector:
    app: technitium
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
    - name: dns-tcp
      port: 53
      protocol: TCP