{{- if .Values.espnCredentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: fantasy-exporter-espn
type: Opaque
stringData:
  ESPN_SWID: {{ .Values.espnCredentials.swid | quote }}
  ESPN_S2: {{ .Values.espnCredentials.s2 | quote }}
{{- end }}